export const EntryTrait = {
  Aquatic: "aquatic",
  CaveDwelling: "cave-dwelling",
  ColdClimate: "cold-climate",
  DesertDwelling: "desert-dwelling",
  ForestDwelling: "forest-dwelling",
  MountainDwelling: "mountain-dwelling",
  SkyDwelling: "sky-dwelling",
  Volcanic: "volcanic",
  Arms: "arms",
  Beak: "beak",
  Claws: "claws",
  Fangs: "fangs",
  Feathers: "feathers",
  Fur: "fur",
  Horns: "horns",
  Shell: "shell",
  Tail: "tail",
  Wings: "wings",
  Burrowing: "burrowing",
  Hunting: "hunting",
  Migratory: "migratory",
  Nocturnal: "nocturnal",
  Sleeping: "sleeping",
  Territorial: "territorial",
  Electric: "electric",
  Fiery: "fiery",
  Icy: "icy",
  Luminous: "luminous",
  Poisonous: "poisonous",
  Psychic: "psychic",
  Sonic: "sonic",
} as const;

export type EntryTrait = (typeof EntryTrait)[keyof typeof EntryTrait];

const traitPatterns: Record<EntryTrait, RegExp[]> = {
  [EntryTrait.Aquatic]: [/\b(?:water|sea|ocean|river|lake|stream|waves?|swims?|swimming)\b/i],
  [EntryTrait.CaveDwelling]: [/\b(?:cave|cavern|underground|tunnel)\b/i],
  [EntryTrait.ColdClimate]: [/\b(?:ice|icy|snow|frozen|cold)\b/i],
  [EntryTrait.DesertDwelling]: [/\b(?:desert|sand|sandy)\b/i],
  [EntryTrait.ForestDwelling]: [/\b(?:forest|woods?|trees?)\b/i],
  [EntryTrait.MountainDwelling]: [/\b(?:mountain|mountains|cliff|cliffs|rocky)\b/i],
  [EntryTrait.SkyDwelling]: [/\b(?:sky|air|clouds?)\b/i],
  [EntryTrait.Volcanic]: [/\b(?:volcano|volcanic|lava)\b/i],
  [EntryTrait.Arms]: [/\b(?:arms?|hands?)\b/i],
  [EntryTrait.Beak]: [/\b(?:beak|beaks)\b/i],
  [EntryTrait.Claws]: [/\b(?:claw|claws|talons?)\b/i],
  [EntryTrait.Fangs]: [/\b(?:fang|fangs|teeth|tooth)\b/i],
  [EntryTrait.Feathers]: [/\b(?:feather|feathers|plumage)\b/i],
  [EntryTrait.Fur]: [/\b(?:fur|furry|pelt)\b/i],
  [EntryTrait.Horns]: [/\b(?:horn|horns|antlers?)\b/i],
  [EntryTrait.Shell]: [/\b(?:shell|shells|carapace)\b/i],
  [EntryTrait.Tail]: [/\b(?:tail|tails)\b/i],
  [EntryTrait.Wings]: [/\b(?:wing|wings)\b/i],
  [EntryTrait.Burrowing]: [/\b(?:burrows?|burrowing|digs?|digging)\b/i],
  [EntryTrait.Hunting]: [/\b(?:hunts?|hunting|prey|stalks?)\b/i],
  [EntryTrait.Migratory]: [/\b(?:migrates?|migration|migratory)\b/i],
  [EntryTrait.Nocturnal]: [/\b(?:nocturnal|night|nights)\b/i],
  [EntryTrait.Sleeping]: [/\b(?:sleeps?|sleeping|slumbers?|naps?|napping)\b/i],
  [EntryTrait.Territorial]: [/\b(?:territory|territorial)\b/i],
  [EntryTrait.Electric]: [/\b(?:electric|electricity|lightning|thunder)\b/i],
  [EntryTrait.Fiery]: [/\b(?:fire|fiery|flames?|heat|hot)\b/i],
  [EntryTrait.Icy]: [/\b(?:ice|icy|freezes?|frozen|cold)\b/i],
  [EntryTrait.Luminous]: [/\b(?:glows?|glowing|light|luminous)\b/i],
  [EntryTrait.Poisonous]: [/\b(?:poison|poisonous|toxic|venom)\b/i],
  [EntryTrait.Psychic]: [/\b(?:psychic|telepath|mind)\b/i],
  [EntryTrait.Sonic]: [/\b(?:sound|sounds|sonic|cries?|screams?)\b/i],
};

export const extractEntryTraits = (text: string): EntryTrait[] =>
  (Object.keys(traitPatterns) as EntryTrait[]).filter((trait) =>
    traitPatterns[trait].some((pattern) => pattern.test(text)),
  );